-- MySQL Script generated by MySQL Workbench
-- Tue Jun 20 14:58:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table2` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table2` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table3`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table3` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table3` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table4`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table4` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table4` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table5`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table5` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table5` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`posts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`posts` (
  `id` INT NOT NULL,
  `Nombre` VARCHAR(255) NULL,
  `Usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_Usuario_idx` (`Usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_Usuario`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `id` INT NOT NULL,
  `Comentario` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentario_has_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comentario_has_post` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comentario_has_post` (
  `Comentario_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  PRIMARY KEY (`Comentario_id`, `post_id`),
  INDEX `fk_Comentario_has_post_post1_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_Comentario_has_post_Comentario1_idx` (`Comentario_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comentario_has_post_Comentario1`
    FOREIGN KEY (`Comentario_id`)
    REFERENCES `mydb`.`comentarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Comentario_has_post_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `mydb`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
